### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Hellowlol** [custom-components/nordpool#1]
- [ ] send PR so the nordpool sensor can be async
- [ ] fix typing issues
- [ ] add option handler so we can edit a sensor for webui
- [ ] fix bug when when it’s a new day the sensor displays the old tomorrow values.
